version: '3'
services:
  nestjs:
    build:
      context: ./nestjs-docker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nestjs-docker:/usr/src/app
    depends_on:
      - nextjs

  nextjs:
    build:
      context: ./nextjs-docker
      dockerfile: Dockerfile
    volumes:
      - ./nextjs-docker:/usr/src/app
    ports:
      - "3001:3000"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/swagger-ui/swagger.json 
    volumes:
      - ./swagger-ui:/swagger-ui 